services:
  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - shared-net
    volumes:
      - eureka-server-certs:/app/resources/certs:ro

networks:
  shared-net:
    external: true

volumes:
  eureka-server-certs:
    external: true