services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    env_file:
      - .env.gateway
    ports:
      - "10000:10000"
    volumes:
      - backend_m2:/root/.m2
      - ~/.m2:/root/.m2
      - gateway-certs:/app/resources/certs:ro
    networks:
      - shared-net

volumes:
  mongo_data:
  backend_m2:
  gateway-certs:
    external: true

networks:
  shared-net:
    external: true
