services:
  user-mongodb:
    image: mongo:4.4
    container_name: user-mongodb
    env_file:
      - .env.users
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-net

  users-service:
    build: 
      context: ./service
      dockerfile: dockerfile
    restart: on-failure
    container_name: users-service
    # ports:
      # - "8080:8080"
    env_file:
      - .env.users

    networks:
      - shared-net
    depends_on:
        - user-mongodb
    volumes:
      - gradle-cache:/root/.gradle
      - backend_m2:/root/.m2
      - users-service-certs:/app/resources/certs:ro
    working_dir: /app
volumes:
  gradle-cache:
  mongo_data:
  users-service-certs:
    external: true
networks:
  shared-net:
    external: true