services:
  user-mongodb:
    image: mongo:latest
    container_name: user-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-net

  users-service:
    build: 
      context: ./service
      dockerfile: dockerfile
    restart: on-failure
    container_name: users-service
    # ports:
      # - "8080:8080"
    env_file:
      - .env.users
    environment:
      - JWT_SECRET=${SECURITY_JWT_SECRET_KEY}
      - JWT_EXP=${JWT_EXP}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PWD=${MONGODB_PWD}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGODB_AUTH=${MONGODB_AUTH}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - DISCOVERY=${DISCOVERY}

    networks:
      - shared-net
    depends_on:
        - user-mongodb
    volumes:
      - /home/abdelilah/buy-01/users-service/service/src:/app/src
      - ~/.gradle:/root/.gradle
      - /home/abdelilah/.m2:/root/.m2
      - /home/abdelilah/buy-01/users-service/certs/users-service.p12:/app/resources/certs/users-service.p12:ro
      - /home/abdelilah/buy-01/users-service/certs/truststore.p12:/app/resources/certs/truststore.p12:ro
    working_dir: /app
volumes:
  mongo_data:
networks:
  shared-net:
    external: true