services:
  products-service-mongodb:
    build: ./database
    container_name: products-service-mongodb
    env_file:
      - .env.product
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-net

  products-service:
    build:
      context: ../
      dockerfile: products-service/products/Dockerfile
    container_name: products-service
    env_file:
      - .env.product

    depends_on:
      - products-service-mongodb
    volumes:
      - backend_m2:/root/.m2
      - products-service-certs:/app/resources/certs:ro
    networks:
      - shared-net

volumes:
  mongo_data:
  backend_m2:
  products-service-certs:
    external: true

networks:
  shared-net:
    external: true
