#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <git-commit-sha>"
    exit 1
fi

TARGET_COMMIT="$1"

git cat-file -e "${TARGET_COMMIT}^{commit}" || {
    echo "[ERROR] Invalid commit: ${TARGET_COMMIT}"
    exit 1
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEMP_DIR="$(mktemp -d)"

cleanup() {
    rm -rf "${TEMP_DIR}"
}

trap cleanup EXIT

echo "[CD] Rolling back to commit ${TARGET_COMMIT}"

cd "${ROOT_DIR}"

git archive "${TARGET_COMMIT}" | tar -x -C "${TEMP_DIR}"

copy_if_exists() {
    local src="$1"
    local dst="$2"

    if [[ -f "${src}" ]]; then
        mkdir -p "$(dirname "${dst}")"
        cp "${src}" "${dst}"
        echo "[CD] Copied $(basename "${src}")"
    else
        echo "[WARN] Missing file: ${src}"
    fi
}

copy_dir_if_exists() {
    local src="$1"
    local dst="$2"

    if [[ -d "${src}" ]]; then
        mkdir -p "${dst}"
        cp -R "${src}/." "${dst}/"
        echo "[CD] Copied directory: ${src}"
    fi
}

# ------------------------------------------------------------------
# Copy environment files generated by setup_env.sh
# ------------------------------------------------------------------

copy_if_exists \
    "${ROOT_DIR}/products-service/.env.product" \
    "${TEMP_DIR}/products-service/.env.product"

copy_if_exists \
    "${ROOT_DIR}/users-service/.env.users" \
    "${TEMP_DIR}/users-service/.env.users"

copy_if_exists \
    "${ROOT_DIR}/gateway/.env.gateway" \
    "${TEMP_DIR}/gateway/.env.gateway"

copy_if_exists \
    "${ROOT_DIR}/media-service/.env.media" \
    "${TEMP_DIR}/media-service/.env.media"

copy_if_exists \
    "${ROOT_DIR}/opensearch/.env.opensearch" \
    "${TEMP_DIR}/opensearch/.env.opensearch"

# ------------------------------------------------------------------
# Copy certificates if used by services
# ------------------------------------------------------------------

copy_dir_if_exists \
    "${ROOT_DIR}/certs" \
    "${TEMP_DIR}/certs"

copy_dir_if_exists \
    "${ROOT_DIR}/gateway/certs" \
    "${TEMP_DIR}/gateway/certs"

copy_dir_if_exists \
    "${ROOT_DIR}/products-service/certs" \
    "${TEMP_DIR}/products-service/certs"

copy_dir_if_exists \
    "${ROOT_DIR}/users-service/certs" \
    "${TEMP_DIR}/users-service/certs"

copy_dir_if_exists \
    "${ROOT_DIR}/media-service/certs" \
    "${TEMP_DIR}/media-service/certs"

if ! docker network inspect shared-net >/dev/null 2>&1; then
    echo "[CD] Creating shared-net network"
    docker network create shared-net
fi

ensure_volume() {
    local volume="$1"
    if ! docker volume inspect "${volume}" >/dev/null 2>&1; then
        echo "[CD] Creating Docker volume: ${volume}"
        docker volume create "${volume}" >/dev/null
    fi
}

ensure_volume "media-service_mongo_data"
ensure_volume "media-service_media_storage"
ensure_volume "eureka-server-certs"
ensure_volume "products-service-certs"
ensure_volume "media-service-certs"
ensure_volume "users-service-certs"
ensure_volume "gateway-certs"

sync_volume() {
    local src="$1"
    local volume="$2"
    local container_name="sync-${volume}-$$"

    if [[ ! -d "${src}" ]]; then
        echo "[WARN] Missing certificate directory: ${src}"
        return
    fi

    echo "[CD] Syncing ${src} to Docker volume ${volume}"
    docker run --rm \
        -v "${volume}:/dst" \
        alpine:3.20 \
        sh -c 'rm -rf /dst/*'

    docker run -d --name "${container_name}" \
        -v "${volume}:/dst" \
        alpine:3.20 \
        sh -c 'sleep 300' >/dev/null

    docker cp "${src}/." "${container_name}:/dst/" || {
        docker rm -f "${container_name}" >/dev/null
        return 1
    }
    docker exec "${container_name}" sh -c 'chmod -R go-rwx /dst' || {
        docker rm -f "${container_name}" >/dev/null
        return 1
    }
    docker rm -f "${container_name}" >/dev/null
}

sync_volume "${TEMP_DIR}/certs" "eureka-server-certs"
sync_volume "${TEMP_DIR}/products-service/certs" "products-service-certs"
sync_volume "${TEMP_DIR}/media-service/certs" "media-service-certs"
sync_volume "${TEMP_DIR}/users-service/certs" "users-service-certs"
sync_volume "${TEMP_DIR}/gateway/certs" "gateway-certs"

compose_up() {
    local service="$1"
    local required="${2:-true}"
    local compose_file="${TEMP_DIR}/${service}/docker-compose.yaml"

    if [[ ! -f "${compose_file}" ]]; then
        if [[ "${required}" == "false" ]]; then
            echo "[CD] Skipping ${service}; compose file not present in rollback commit."
            return 0
        fi
        echo "[ERROR] Compose file not found: ${compose_file}"
        return 1
    fi

    echo "[CD] Deploying ${service}"

    if [[ "${service}" == "opensearch" && -f "${TEMP_DIR}/${service}/.env.opensearch" ]]; then
        docker compose \
            --env-file "${TEMP_DIR}/${service}/.env.opensearch" \
            -f "${compose_file}" \
            up -d --build
    else
        docker compose \
            -f "${compose_file}" \
            up -d --build
    fi
}

compose_up "eureka-server"
compose_up "redis"
compose_up "opensearch" "false"
compose_up "kafka"
compose_up "products-service"
compose_up "media-service"
compose_up "users-service"
compose_up "gateway"

echo "[CD] Rollback completed successfully."
