#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <git-commit-sha>"
    exit 1
fi

TARGET_COMMIT="$1"

git cat-file -e "${TARGET_COMMIT}^{commit}" || {
    echo "[ERROR] Invalid commit: ${TARGET_COMMIT}"
    exit 1
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEMP_DIR="$(mktemp -d)"

# shellcheck source=scripts/ci/docker_cleanup.sh
source "${ROOT_DIR}/scripts/ci/docker_cleanup.sh"

cleanup() {
    rm -rf "${TEMP_DIR}"
}

trap cleanup EXIT

echo "[CD] Rolling back to commit ${TARGET_COMMIT}"

cd "${ROOT_DIR}"

git archive "${TARGET_COMMIT}" | tar -x -C "${TEMP_DIR}"

copy_if_exists() {
    local src="$1"
    local dst="$2"

    if [[ -f "${src}" ]]; then
        mkdir -p "$(dirname "${dst}")"
        cp "${src}" "${dst}"
        echo "[CD] Copied $(basename "${src}")"
    else
        echo "[WARN] Missing file: ${src}"
    fi
}

copy_dir_if_exists() {
    local src="$1"
    local dst="$2"

    if [[ -d "${src}" ]]; then
        mkdir -p "${dst}"
        cp -R "${src}/." "${dst}/"
        echo "[CD] Copied directory: ${src}"
    fi
}

# ------------------------------------------------------------------
# Copy environment files generated by setup_env.sh
# ------------------------------------------------------------------

copy_if_exists \
    "${ROOT_DIR}/products-service/.env.product" \
    "${TEMP_DIR}/products-service/.env.product"

copy_if_exists \
    "${ROOT_DIR}/users-service/.env.users" \
    "${TEMP_DIR}/users-service/.env.users"

copy_if_exists \
    "${ROOT_DIR}/gateway/.env.gateway" \
    "${TEMP_DIR}/gateway/.env.gateway"

copy_if_exists \
    "${ROOT_DIR}/media-service/.env.media" \
    "${TEMP_DIR}/media-service/.env.media"

copy_if_exists \
    "${ROOT_DIR}/payments-service/.env.payments" \
    "${TEMP_DIR}/payments-service/.env.payments"

copy_if_exists \
    "${ROOT_DIR}/opensearch/.env.opensearch" \
    "${TEMP_DIR}/opensearch/.env.opensearch"

# ------------------------------------------------------------------
# Copy certificates if used by services
# ------------------------------------------------------------------

copy_dir_if_exists \
    "${ROOT_DIR}/certs" \
    "${TEMP_DIR}/certs"

copy_dir_if_exists \
    "${ROOT_DIR}/gateway/certs" \
    "${TEMP_DIR}/gateway/certs"

copy_dir_if_exists \
    "${ROOT_DIR}/products-service/certs" \
    "${TEMP_DIR}/products-service/certs"

copy_dir_if_exists \
    "${ROOT_DIR}/users-service/certs" \
    "${TEMP_DIR}/users-service/certs"

copy_dir_if_exists \
    "${ROOT_DIR}/media-service/certs" \
    "${TEMP_DIR}/media-service/certs"

if ! docker network inspect shared-net >/dev/null 2>&1; then
    echo "[CD] Creating shared-net network"
    docker network create shared-net
fi

ensure_volume() {
    local volume="$1"
    if ! docker volume inspect "${volume}" >/dev/null 2>&1; then
        echo "[CD] Creating Docker volume: ${volume}"
        docker volume create "${volume}" >/dev/null
    fi
}

ensure_volume "media-service_mongo_data"
ensure_volume "media-service_media_storage"
ensure_volume "eureka-server-certs"
ensure_volume "products-service-certs"
ensure_volume "media-service-certs"
ensure_volume "payments-service-certs"
ensure_volume "users-service-certs"
ensure_volume "gateway-certs"
ensure_volume "prometheus-certs"

if [[ -f "${TEMP_DIR}/scripts/setup-cert-volumes.sh" && -f "${TEMP_DIR}/certs/truststore.p12" ]]; then
    echo "[CD] Syncing rollback certificate and key Docker volumes."
    bash "${TEMP_DIR}/scripts/setup-cert-volumes.sh" \
        --cert-dir "${TEMP_DIR}/certs" \
        --jwt-private "${TEMP_DIR}/users-service/certs/jwt-private.pem" \
        --jwt-public "${TEMP_DIR}/gateway/certs/jwt-public.pem" \
        --clean
else
    echo "[CD] Skipping rollback certificate volume sync; no rollback cert bundle found."
fi

docker_cleanup
docker_cleanup_aggressive
docker_ensure_space

compose_up() {
    local service="$1"
    local required="${2:-true}"
    local compose_file="${TEMP_DIR}/${service}/docker-compose.yaml"

    if [[ ! -f "${compose_file}" ]]; then
        if [[ "${required}" == "false" ]]; then
            echo "[CD] Skipping ${service}; compose file not present in rollback commit."
            return 0
        fi
        echo "[ERROR] Compose file not found: ${compose_file}"
        return 1
    fi

    echo "[CD] Deploying ${service}"

    docker_ensure_space

    if [[ "${service}" == "opensearch" && -f "${TEMP_DIR}/${service}/.env.opensearch" ]]; then
        if ! docker compose \
            --env-file "${TEMP_DIR}/${service}/.env.opensearch" \
            -f "${compose_file}" \
            up -d --build; then
            docker_cleanup_aggressive
            return 1
        fi
    else
        if ! docker compose \
            -f "${compose_file}" \
            up -d --build; then
            docker_cleanup_aggressive
            return 1
        fi
    fi

    docker_build_cleanup
}

compose_up "eureka-server"
compose_up "redis"
compose_up "opensearch" "false"
compose_up "kafka"
compose_up "products-service"
compose_up "media-service"
compose_up "users-service"
compose_up "payments-service" "false"
compose_up "gateway"

docker_cleanup

echo "[CD] Rollback completed successfully."
