services:
  media-service-mongodb:
    build:
      context: ./database
      dockerfile: dockerfile
    container_name: media-service-mongodb
    env_file:
      - .env.media
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-net

  media-service:
    build:
      context: ../
      dockerfile: ./media-service/media/Dockerfile
    container_name: media-service
    ports:
      - "8888:8888"
    env_file:
      - .env.media
    environment:
      SPRING_APPLICATION_NAME: media
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DISCOVERY: http://eureka-server:8761/eureka
      JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/app/resources/certs/truststore.p12 -Djavax.net.ssl.trustStorePassword=123456_certTest -Djavax.net.ssl.trustStoreType=PKCS12 -Djavax.net.ssl.keyStore=/app/resources/certs/media-service.p12 -Djavax.net.ssl.keyStorePassword=123456_certTest -Djavax.net.ssl.keyStoreType=PKCS12
    depends_on:
      - media-service-mongodb
    volumes:
      - media_m2:/root/.m2
      - media-certs:/app/resources/certs:ro
      - ./certs/media-service.p12:/app/resources/certs/media-service.p12:ro
      # - ./certs/truststore.p12:/app/resources/certs/truststore.p12:ro
    networks:
      - shared-net

volumes:
  mongo_data:
  media_m2:
  media-certs:
    external: true

networks:
  shared-net:
    external: true
