services:
  payments-service:
    build:
      context: ..
      dockerfile: payments-service/Dockerfile
    container_name: payments-service
    restart: on-failure
    env_file:
      - .env.payments
    environment:
      CERTIFICATE_PATH: file:/app/resources/certs/payments-service.p12
      TRUSTSTORE_PATH: file:/app/resources/certs/truststore.p12
    volumes:
      - payments-service-certs:/app/resources/certs:ro
    networks:
      - shared-net

networks:
  shared-net:
    external: true

volumes:
  payments-service-certs:
    external: true
